## Tensors

In [8]:
import torch

x = torch.empty(2, 5)
x.fill_(1.125)  # in-place operation: '_'
x.mean()
x.sum()
x.sum().item()  # getting python scalar

11.25

In [11]:
x = torch.tensor([10, 20, 30])
y = torch.tensor([11, 21, 31])
x + y
x * y
x**2

tensor([100, 400, 900])

In [14]:
matrix = torch.tensor([[0, 0, 3],
                       [0, 2, 0],
                       [1, 0, 0]])
matrix.mv(x)  # matrix-vector product
matrix @ x  # matrix-vector product

tensor([90, 40, 10])

In [23]:
x = torch.empty(2, 4).random_(10)
x

tensor([[6., 7., 1., 4.],
        [2., 3., 7., 8.]])

In [26]:
x[0]
x[0, :]
x[:, 0]
x[:, 1:3]

tensor([[7., 1.],
        [3., 7.]])

In [35]:
y = torch.empty(3).normal_()
print(y)
m = torch.empty(3, 3).normal_()

tensor([0.6607, 0.3201, 0.1577])


In [36]:
q, _ = torch.lstsq(y, m)
q, _
torch.mm(m, q)

tensor([[0.6607],
        [0.3201],
        [0.1577]])

## High dimension tensors

In [39]:
x = torch.zeros(1, 3)
print(x.dtype, x.device)

x = x.long()
print(x.dtype, x.device)

x.to('cuda')
print(x.device)

torch.float32 cpu
torch.int64 cpu


RuntimeError: No CUDA GPUs are available

In [46]:
x = torch.empty(2, 3).random_()
print(x)
print(x.t())
print(x.view(-1))
print(x.view(3, -1))

x.view(1, 2, 3)  # torch of the same shape but with one channel dimension
x.expand(3, 2, 3) # expand first channel so copy tensor 3 times

tensor([[  541552.,  8713293., 10281259.],
        [ 3332778., 11426502., 14744735.]])
tensor([[  541552.,  3332778.],
        [ 8713293., 11426502.],
        [10281259., 14744735.]])
tensor([  541552.,  8713293., 10281259.,  3332778., 11426502., 14744735.])
tensor([[  541552.,  8713293.],
        [10281259.,  3332778.],
        [11426502., 14744735.]])


tensor([[[  541552.,  8713293., 10281259.],
         [ 3332778., 11426502., 14744735.]],

        [[  541552.,  8713293., 10281259.],
         [ 3332778., 11426502., 14744735.]],

        [[  541552.,  8713293., 10281259.],
         [ 3332778., 11426502., 14744735.]]])

## Tensor internals

We can access the storage of the tensor

In [48]:
x = torch.zeros(2, 4)
x.storage()

 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
[torch.FloatStorage of size 8]